# Generated by Django 2.1 on 2020-04-13 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo_item',
            old_name='context',
            new_name='content',
        ),
    ]
